/**
 * The capability keys of the server's catalog
 * (`server/src/common/permissions/permission-catalog.ts`). The server decides
 * who holds which and answers `GET /permissions/me`; the client only hides
 * what the list does not contain. `permission-keys.test.ts` compares this
 * list with the server's.
 */
export const PERMISSION_KEYS = [
  "students.list",
  "students.profile",
  "students.details",
  "students.manage",
  "students.enroll",
  "students.sms",
  "students.initial-balance",
  "groups.view",
  "groups.manage",
  "lessons.change",
  "lessons.change-delete",
  "attendance.mark",
  "attendance.fix",
  "leads.view",
  "leads.manage",
  "leads.setup",
  "leads.forms",
  "outreach.view",
  "calls.log",
  "mock.view",
  "mock.manage",
  "mock.payments",
  "payments.view",
  "payments.create",
  "payments.correct",
  "debt.view",
  "debt.promise",
  "balance.withdraw",
  "refunds.create",
  "debt.write-off",
  "balance.adjust",
  "money.undo",
  "payments.gateway-log",
  "expenses.view",
  "expenses.manage",
  "cash.manage",
  "salary.view",
  "salary.rate",
  "salary.pay",
  "salary.rate-edit",
  "salary.close",
  "reports.finance",
  "reports.payments",
  "reports.students",
  "reports.leads",
  "teachers.view",
  "teachers.manage",
  "employees.view",
  "employees.manage",
  "employees.invite",
  "comments.write",
  "comments.delete",
  "settings.reference",
  "courses.create",
  "settings.branches",
  "settings.payment",
  "settings.telegram-groups",
  "settings.absence-pause",
  "telegram.announce",
  "settings.company",
  "settings.archive",
  "dashboard.view",
  "daf.activity",
  "media.view",
] as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[number];
