import type { Yangilik } from "./turlar";

/**
 * Foydalanuvchiga ko'rinadigan har o'zgarish shu yerga bitta yozuv qo'shadi
 * (o'sha PR'da). Eng yangisi tepada.
 */
export const yangiliklar: Yangilik[] = [
  {
    sana: "2026-10-02",
    sarlavha: "Menyu va tugmalar rolga moslandi",
    matn: "Kassirga «Guruhlar» menyusi ko'rinmaydi, guruh nomi unga havolasiz chiqadi va o'quvchi profilida «Chiqarish» tugmasi yo'q. «Qarzdorlik» sahifasidagi «Markaz qoplagani» tabi kassirga ochiladi, «Natijani kiritish» va muzlatilgan pulni siljitish tugmalari esa unga ko'rinmaydi. Administrator «Ish haqi» sahifasidagi oylik, avans va to'lov ma'lumotlarini server tomondan ham ko'ra olmaydi, qidiruvda xodimlar unga chiqmaydi.",
    rollar: [1, 2, 3, 5],
    sahifa: { bolim: "boshlash", sahifa: "rollar-va-huquqlar" },
  },
  {
    sana: "2026-10-02",
    sarlavha: "Boshqa filialdagi guruh yoki o'quvchi sahifasi",
    matn: "Tanlangan filialda ochilmagan guruh yoki o'quvchi sizning boshqa filialingizda bo'lsa, sahifa «Guruh boshqa filialda» (yoki «O'quvchi boshqa filialda») deb yozadi va shu filialga o'tish tugmasini beradi. Ilgari bunday sahifa «Guruh topilmadi» yoki «O'quvchi topilmadi» deb chiqardi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "boshlash", sahifa: "rollar-va-huquqlar" },
  },
  {
    sana: "2026-10-02",
    sarlavha: "Guruhga qo'shish oynasi pulni oldindan ko'rsatadi",
    matn: "Guruh tanlangach oyna oylik narxni, birinchi hisob summasini (qo'shilish kunidan boshlab, chegirma bilan), balansni va «To'lash kerak (taxminan)» ni ko'rsatadi. Boshqa guruhga o'tkazishda «Eski guruhdan qaytadi» qatori ham chiqadi. Ilgari oyna kursning to'liq narxini ko'rsatardi va oy o'rtasidagi qisman hisobni hisobga olmasdi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "oquvchilar", sahifa: "guruhga-qoshish" },
  },
  {
    sana: "2026-10-02",
    sarlavha: "Botda ro'yxatdan o'tgan o'quvchidan oy puli darhol olinadi",
    matn: "Telegram botda ustoz va guruhni tanlab o'zi ro'yxatdan o'tgan o'quvchining qo'shilgan oyi ro'yxatdan o'tgan zahoti hisoblanadi. Ilgari hisob tungi yurishda yozilardi va oyning oxirgi dars kuni ro'yxatdan o'tgan o'quvchi o'sha oy uchun to'lamay qolardi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "oquvchilar", sahifa: "guruhga-qoshish" },
  },
  {
    sana: "2026-10-02",
    sarlavha: "O'quvchi kartasining «To'lovlar» tabida ikki jadval",
    matn: "Tabda endi PDF dagidek ikkita jadval bor: «To'lovlar» (har to'lov va u qaysi oyga yozilgani) va «Oylar bo'yicha» (har oyning narxi, to'langani va qarzi). «Batafsil» da «Izohlar» va «Barcha yozuvlar» qoldi. Ilgari to'lovlar yopiq bo'limda turardi, oylar jadvalida esa «Oy oxirida» ustuni bor edi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "oquvchilar", sahifa: "oquvchi-kartasi" },
  },
  {
    sana: "2026-10-01",
    sarlavha: "Sinov darsi: bitta darsga kelgan o'quvchiga oyning puli qaytadi",
    matn: "Hamma guruhda ko'pi bilan 1 ta darsga kelgan o'quvchi guruhdan chiqarilsa yoki chetlatilsa, oyning to'liq puli balansga qaytadi va ustozga o'sha oyning darslari uchun haq yozilmaydi (shartnoma 3.5). Javobsiz «Dars bo'ldimi?» savoli natijani o'zgartira olsa, chiqarish avval javobni kutadi. CEO qoidani Sozlamalar → «To'lov» da o'chira oladi. Ilgari bunday o'quvchiga ham faqat o'tilmagan darslar puli qaytardi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "oquvchilar", sahifa: "guruhdan-chiqarish" },
  },
  {
    sana: "2026-10-01",
    sarlavha: "To'lamagan o'quvchi oyning 2-darsidan davomatga qo'yilmaydi",
    matn: "Oylik kursda o'quvchi oyning o'zining 1-darsiga to'lovsiz keladi; 2-darsdan boshlab to'lagan puli shu darsgacha yetmasa, davomatda unga «Keldi», «Kelmadi» va «Kechikdi» qo'yib bo'lmaydi, faqat «Sababli». Qatorda «To'lov qilinmagan · darsga qo'yilmaydi» yozuvi va administratorga «To'lov qabul qilish» tugmasi chiqadi; QR bilan ham skanerlay olmaydi. Ustozga bunday o'quvchi uchun haq yozilmaydi. CEO qoidani Sozlamalar → «To'lov» da o'chira oladi. Ilgari qarzdor o'quvchi har darsda boshqalar kabi belgilanardi.",
    rollar: [1, 2, 3, 4],
    sahifa: { bolim: "davomat", sahifa: "darsga-qoyish" },
  },
  {
    sana: "2026-10-01",
    sarlavha: "Kechikkan o'quvchi «Kechikdi» bo'lib, daqiqasi bilan yoziladi",
    matn: "O'qituvchi davomatni saqlagandan keyin, dars davom etayotganda administrator, direktor yoki CEO darsda bo'lmagan o'quvchini «Keldi» qilsa, tizim uni «Kechikdi» deb yozadi va qatorga «N daqiqa kechikdi» qo'shadi. Ilgari kechikkani va necha daqiqa kechikkani yo'qolardi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "davomat", sahifa: "davomat-olish" },
  },
  {
    sana: "2026-10-01",
    sarlavha: "Davomat necha daqiqa oldin ochilishini CEO belgilaydi",
    matn: "Sozlamalar → «To'lov» sahifasida «Davomat dars boshlanishidan necha daqiqa oldin ochiladi» maydoni paydo bo'ldi: 0 dan 60 gacha, boshlang'ich qiymat — 10. Uni faqat CEO o'zgartiradi, filial direktori ko'radi. Ilgari 10 daqiqa o'zgarmas edi.",
    rollar: [1, 2],
    sahifa: { bolim: "davomat", sahifa: "davomat-olish" },
  },
  {
    sana: "2026-10-01",
    sarlavha: "Davomat eslatmalari «Dars bo'ldimi?» bilan birga ketadi",
    matn: "Dars tugab davomat olinmasa, o'qituvchi va administratorga «Davomat olinmadi» boradi, administratorga esa «Dars bo'ldimi?» topshirig'i ochiladi. Dars tugashiga 30 daqiqa qolganda administratorga «O'qituvchi hali davomat olmadi» keladi: unda davomat olinmasa ustozga haq yozilmasligi aytiladi. «Bo'ldi» deb davomat kech kiritilsa, ustozga «Dars haqi yozilmadi» keladi. Ilgari xabarlar «Davomat belgilanmadi» va «O'qituvchiga eslatib qo'ying» deb atalardi.",
    rollar: [1, 2, 3, 4],
    sahifa: { bolim: "davomat", sahifa: "eslatmalar" },
  },
  {
    sana: "2026-09-30",
    sarlavha: "Davomat hamma uchun faqat dars vaqtida olinadi",
    matn: "Yangi davomatni endi administrator, filial direktori va CEO ham faqat dars kuni, dars boshlanishidan 10 daqiqa oldin to dars tugaguncha oladi. Dars tugagach yangi davomat kiritishning yagona yo'li — «Dars bo'ldimi?» savoliga «Bo'ldi» deb javob berish. Saqlangan davomatni tuzatish dars tugagach ham ochiq, oldindan belgilash esa dars tugaguncha mumkin. Ilgari ular istalgan dars kuniga davomat kirita olardi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "davomat", sahifa: "davomat-olish" },
  },
  {
    sana: "2026-09-30",
    sarlavha: "Qo'llanma ishga tushdi",
    matn: "Tizim qoidalari endi admin panel ichida. Har sahifadagi «?» tugmasi shu sahifaning qoidasini ochadi.",
    sahifa: { bolim: "boshlash", sahifa: "interfeys" },
  },
  {
    sana: "2026-09-30",
    sarlavha: "«Topshiriqlar»da tizim topshirig'i: «Dars bo'ldimi?»",
    matn: "Dars tugaguncha davomat olinmasa, filial administratorlariga «Tizim» nomidan «Dars bo'ldimi?» topshirig'i keladi. Javobni kartaning o'zida berasiz: «Bo'ldi» davomatni kech kiritadi va ustozga bu dars uchun haq yozilmaydi, «Bo'lmadi» darsni bekor qiladi yoki ko'chiradi. Ilgari tizim «dars bo'lmadi» bilan «davomat unutildi»ni ajrata olmasdi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "davomat", sahifa: "dars-boldimi" },
  },
  {
    sana: "2026-09-30",
    sarlavha: "Bildirishnomani bossangiz, tegishli sahifa ochiladi",
    matn: "Bildirishnomalar ro'yxatida xabarni bossangiz, tegishli o'quvchi, guruh, lid yoki xodim sahifasi ochiladi. Sahifani ocha olmaydigan xodimga (masalan, kassirga guruh sahifasi) sahifa ochilmaydi: xabar faqat o'qilgan bo'ladi. Ilgari ko'p xabarlar to'g'ri sahifani ochmasdi.",
    sahifa: { bolim: "boshlash", sahifa: "interfeys" },
  },
  {
    sana: "2026-09-30",
    sarlavha: "Topshiriq muddatini sana bilan belgilash mumkin",
    matn: "Topshiriq formasida «Muddat» sanasini tanlasangiz, muddat shu kunning 18:00 si (Toshkent vaqti) bo'ladi; yakshanbani tanlab bo'lmaydi. Ilgari sana bilan yuborilgan topshiriqni tizim rad etardi.",
    rollar: [1, 2],
    sahifa: { bolim: "boshlash", sahifa: "topshiriqlar" },
  },
  {
    sana: "2026-09-30",
    sarlavha: "Topshiriq kartasidagi havolalar to'g'rilandi",
    matn: "Lidga yozilgan topshiriqning havolasi endi «Lidlar» sahifasida shu lidning kartochkasini ochadi. Xodim sahifasiga havola faqat CEO va filial direktoriga chiqadi. Ilgari lidning havolasi mavjud bo'lmagan sahifaga olib borardi, administrator esa xodim havolasidan «Sozlamalar» sahifasiga qaytarilardi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "boshlash", sahifa: "topshiriqlar" },
  },
  {
    sana: "2026-09-30",
    sarlavha: "«Statusni o'zgartirish» oynasidan arxivlash ishlaydi",
    matn: "O'quvchini «Statusni o'zgartirish» oynasida «Arxivlash» kartochkasi bilan, sababni ro'yxatdan tanlab arxivlash mumkin. Ilgari sabab ro'yxatdan tanlanganda tizim so'rovni rad etardi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "oquvchilar", sahifa: "chetlatish-va-arxiv" },
  },
  {
    sana: "2026-09-30",
    sarlavha: "CEO o'quvchiga boshlang'ich balans kirita oladi",
    matn: "O'quvchi kartasidagi «To'lov» menyusida CEO uchun «Boshlang'ich balans» yana ko'rinadi: boshqa tizimdan o'tgan o'quvchining oldindan to'langan puli bir marta kiritiladi. Ilgari menyuda bu tanlov chiqmasdi.",
    rollar: [1],
    sahifa: { bolim: "oquvchilar", sahifa: "oquvchi-kartasi" },
  },
  {
    sana: "2026-09-29",
    sarlavha: "Bekor qilingan darsning puli darhol qaytadi",
    matn: "Markaz darsni bekor qilsa, oylik kursdagi har o'quvchiga shu dars puli darhol balansga qaytadi: o'quvchi o'sha kuni davomatda belgilanganmi-yo'qmi, farqi yo'q. Guruhdan chiqqan o'quvchiga ham qaytadi. Ilgari pul faqat o'sha kuni belgilanganlarga tegar va keyingi oy hisobidan ayirilardi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "tolovlar", sahifa: "oylik-tolov" },
  },
  {
    sana: "2026-09-29",
    sarlavha: "O'qituvchi davomatni faqat bugungi darsga oladi",
    matn: "O'qituvchi davomatni faqat bugungi dars kuni, dars boshlanishidan 10 daqiqa oldin to dars tugaguncha oladi. Boshqa kunni saqlashda tizim rad etadi. Ilgari o'tgan yoki kelgusi kunni ham saqlab bo'lardi.",
    rollar: [1, 2, 3, 4],
    sahifa: { bolim: "davomat", sahifa: "davomat-olish" },
  },
  {
    sana: "2026-09-27",
    sarlavha: "O'quvchiga oylik to'lov xabari",
    matn: "Oylik kursdagi o'quvchiga Telegramda ikki xabar boradi: oy hisobi yozilgan kuni oyning to'lovi va muddati, qarzdorga esa oyning 2-darsidan bir kun oldin eslatma. CEO xabarlarni Sozlamalar → «To'lov» da o'chirishi mumkin.",
    rollar: [1, 2, 3, 5],
    sahifa: { bolim: "tolovlar", sahifa: "oylik-tolov" },
  },
  {
    sana: "2026-09-27",
    sarlavha: "To'lov oynasi oylik kurs uchun tavsiya beradi",
    matn: "Oylik kursdagi o'quvchiga to'lov qayd qilayotganda oyna qarz va keyingi oy summasini ko'rsatadi, tezkor tugmalar esa «Qarzni yopish», «Qarz + keyingi oy», «1 oy» va «2 oy» bo'ladi.",
    rollar: [1, 2, 3, 5],
    sahifa: { bolim: "tolovlar", sahifa: "tolov-qayd-qilish" },
  },
  {
    sana: "2026-09-27",
    sarlavha: "Guruhdan chiqarishda pul qoidasi (shartnoma 6.2)",
    matn: "Guruhdan chiqarish va chetlatish oynasida «Pul (shartnoma bo'yicha)» bloki paydo bo'ldi: u tanlangan tartib bilan balansga nima bo'lishini oldindan ko'rsatadi. 01.10.2026 dan o'quvchi o'zi to'xtatsa va oyning 40% idan ko'pi o'tgan bo'lsa, oylik puli qaytmaydi. «Darajani tugatdi» tartibida o'tilmagan darslar puli qaytadi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "oquvchilar", sahifa: "guruhdan-chiqarish" },
  },
  {
    sana: "2026-09-27",
    sarlavha: "O'quvchi birinchi kirishda jins va tug'ilgan sanani kiritadi",
    matn: "O'quvchi portalga yoki ilovaga birinchi marta kirganda jinsi va tug'ilgan sanasini kiritadi. Telefonni SMS kod bilan tasdiqlash qadami server sozlamasi bilan yoqiladi («Sozlamalar» sahifasida bunday tugma yo'q). O'quvchi kartasida «Telefon tasdiqlangan» va «Telegram botda ro'yxatdan o'tgan» belgilari alohida ko'rinadi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "oquvchilar", sahifa: "yangi-oquvchi" },
  },
  {
    sana: "2026-09-27",
    sarlavha: "Muzlatishdan qaytganda faqat qaytgan kundan keyingi darslar hisoblanadi",
    matn: "Oylik kursdagi o'quvchi muzlatishdan qaytganda balansdan faqat qaytgan kundan keyingi darslar puli yechiladi: muzlatilgan paytda o'tgan darslar va qaytgan kunning o'zi hisoblanmaydi. Muzlatish oynasi oylik kurs uchun qaytadigan pulni ko'rsatadi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "oquvchilar", sahifa: "muzlatish" },
  },
  {
    sana: "2026-09-27",
    sarlavha: "Guruh holati yo to'liq o'zgaradi, yo umuman",
    matn: "Guruhni «Bekor qilingan» yoki «Tugallangan» qilganingizda holat, o'quvchilarni chiqarish, pulni qaytarish, tarix va avtomatik bitirish birga bajariladi. Biror qadam yiqilsa, guruh holati o'zgarmaydi va «Guruh holati o'zgarmadi, hech narsa saqlanmadi. Qayta urinib ko'ring.» xabari chiqadi. Ilgari guruh yopilib, o'quvchilar unda ochiq qolib ketishi mumkin edi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "guruhlar", sahifa: "guruh-holatlari" },
  },
  {
    sana: "2026-09-26",
    sarlavha: "Barcha kurslar oylik to'lovga o'tdi",
    matn: "01.09.2026 dan barcha kurslar oylik to'lovda; tizimdagi o'tish 26.09.2026 da bajarildi va sentabr oyi qaytadan oylik hisoblandi. Endi oy hisobi oy boshida yoziladi va davomat pulga tegmaydi. Dars paketi tizimda saqlanib qolgan.",
    rollar: [1, 2, 3, 5],
    sahifa: { bolim: "tolovlar", sahifa: "tolov-turlari" },
  },
  {
    sana: "2026-09-26",
    sarlavha: "Muzlatilgan o'quvchini to'g'ridan-to'g'ri chetlatish mumkin",
    matn: "Muzlatilgan o'quvchi qaytmasa, uni avval «Faol» qilmasdan «Chetlatilgan» qilish mumkin. Bu bitta ketish hisoblanadi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "oquvchilar", sahifa: "chetlatish-va-arxiv" },
  },
  {
    sana: "2026-09-26",
    sarlavha: "O'quvchi kartasida «To'lovlar» tabi yangi hisobotga o'tdi",
    matn: "«To'lovlar» tabi endi «To'lovlar hisoboti»ni ko'rsatadi: bitta gapli javob, «Oylar bo'yicha» jadvali, «To'lovlar qayerga ketdi» bo'limi va PDF. Hisobot balans bilan so'mma-so'm mos keladi; farq chiqsa, u yashirilmaydi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "oquvchilar", sahifa: "oquvchi-kartasi" },
  },
  {
    sana: "2026-09-26",
    sarlavha: "Guruh yopilganda muzlatilgan o'quvchi ham chiqariladi",
    matn: "Guruh «Bekor qilingan» yoki «Tugallangan» qilinsa, muzlatilgan o'quvchining yozilishi ham yopiladi: u guruhdan chiqarilgan hisoblanadi (tugallangan guruhda muzlatilgan o'quvchi bitirmaydi). Guruhni o'chirish oynasi endi nechta o'quvchi chiqishini oldindan ko'rsatadi, o'chirilgan guruh esa arxivdan bo'sh qaytadi. Ilgari muzlatilgan o'quvchi yopilgan guruhda «Muzlatilgan» bo'lib qolardi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "guruhlar", sahifa: "guruh-holatlari" },
  },
  {
    sana: "2026-09-25",
    sarlavha: "Oylik kursda boshqa guruhga o'tkazilsa, eski oy puli qisqaradi",
    matn: "O'quvchi oy o'rtasida oylik kursdan boshqa guruhga o'tkazilsa, eski guruhning shu oydagi hisobi o'tkazish kunigacha o'tilgan darslarga qisqaradi va o'tilmagan darslar puli balansga qaytadi. Yangi kurs o'z narxida, qolgan darslar uchun olinadi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "oquvchilar", sahifa: "guruhga-qoshish" },
  },
  {
    sana: "2026-09-24",
    sarlavha: "Boshqa qurilmalardan chiqish",
    matn: "Profil sahifasida «Boshqa qurilmalardan chiqish» tugmasi paydo bo'ldi. Parol o'zgarganda (Profilda, SMS orqali yoki rahbar yozib bersa) ham boshqa qurilmalardagi kirishlar tugaydi. Profilda o'zingiz o'zgartirsangiz yoki tugmani bossangiz, shu qurilmada qolasiz.",
    sahifa: { bolim: "boshlash", sahifa: "tizimga-kirish" },
  },
  {
    sana: "2026-09-24",
    sarlavha: "Telefon raqam joriy parol bilan o'zgaradi",
    matn: "Profilda telefon raqamni o'zgartirganda «Joriy parol» so'raladi. Eski raqam kirish uchun ishlamay qoladi: keyingi safar yangi raqam bilan kirasiz.",
    sahifa: { bolim: "boshlash", sahifa: "tizimga-kirish" },
  },
  {
    sana: "2026-09-24",
    sarlavha: "Rol berish va xodim hisobini o'zgartirish qoidalari",
    matn: "Rolni faqat o'zingizdan pastdagilarga bera olasiz. Xodim hisobini faqat undan yuqori rahbar o'zgartiradi: direktor boshqa direktorning hisobini o'zgartira olmaydi, administrator esa hech kimning hisobini o'zgartira olmaydi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "boshlash", sahifa: "rollar-va-huquqlar" },
  },
  {
    sana: "2026-09-24",
    sarlavha: "Bloklangan xodim darhol to'xtaydi",
    matn: "«To'xtatilgan» yoki «Ishdan bo'shatilgan» qilingan, yoki arxivlangan xodim keyingi harakatidayoq to'xtaydi va «Hisobingiz bloklangan» xabarini ko'radi. Ilgari u bir soatgacha ishlashda davom etardi.",
    rollar: [1, 2],
    sahifa: { bolim: "boshlash", sahifa: "rollar-va-huquqlar" },
  },
  {
    sana: "2026-09-24",
    sarlavha: "Kartadagi telefon raqam o'zgarsa, o'quvchining kirish raqami ham o'zgaradi",
    matn: "O'quvchi kartasidagi «Telefon raqam»ni o'zgartirsangiz, kirish raqami ham shu zahoti o'zgaradi: eski raqam kirish uchun ishlamay qoladi, parol o'zgarmaydi. Ilgari faqat karta o'zgarardi, kirish esa eski raqamda qolardi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "oquvchilar", sahifa: "yangi-oquvchi" },
  },
  {
    sana: "2026-09-24",
    sarlavha: "Arxivlangan o'quvchi kira olmaydi",
    matn: "O'quvchi kartasini arxivga o'tkazsangiz, uning kirish hisobi ham yopiladi va raqami bo'shaydi. Karta arxivdan tiklansa, hisob ham qaytadi. Chetlatilgan, muzlatilgan va bitirgan o'quvchining hisobi ochiq qoladi: u qarzini portalda to'laydi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "oquvchilar", sahifa: "chetlatish-va-arxiv" },
  },
  {
    sana: "2026-09-24",
    sarlavha: "Avtomatik pauza: xabarlar dars kuni kechqurun boradi",
    matn: "Avtomatik pauza yoqilganda ketma-ket dars qoldirgan o'quvchiga Telegramda endi uch bosqichli xabar boradi: birinchi qoldirishda yengil so'rov, ogohlantirish chegarasida ogohlantirish, pauza chegarasida pauza haqida xabar. Birinchi ikki bosqich dars kuni soat 20:30 da boradi (ilgari ertasi ertalab), pauza ertasi ertalab soat 07:30 da.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "davomat", sahifa: "avtomatik-pauza" },
  },
  {
    sana: "2026-09-22",
    sarlavha: "Qarz kechirish o'chirildi",
    matn: "CEO 21.09.2026 da qarz kechirilmasligini belgiladi: Sozlamalar → «To'lov» dagi «Qarz kechirishga ruxsat» o'chiq turadi va qarz butun tarixi bilan saqlanadi. Ilgari kechirilgan qarzlar «Qarzdorlik» sahifasidagi «Kechirilganlar» tabida ko'rinib turadi. Sozlamani faqat CEO o'zgartiradi.",
    rollar: [1, 2, 3, 5],
    sahifa: { bolim: "tolovlar", sahifa: "qarzdorlik" },
  },
  {
    sana: "2026-09-22",
    sarlavha: "«Qarzdorlik» sahifasida «Muzlatilgan puli» tabi",
    matn: "Muzlatilgan, balansida pul qolgan va muzlatilganiga 30 kundan ortiq bo'lgan o'quvchilar ro'yxati paydo bo'ldi. Qator menyusidan pulni o'quvchiga qaytarish yoki markaz hisobiga o'tkazish mumkin.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "tolovlar", sahifa: "qarzdorlik" },
  },
  {
    sana: "2026-09-22",
    sarlavha: "Sozlamalar → «To'lov» va kursning to'lov modeli",
    matn: "Sozlamalar → «To'lov» sahifasida yangi kurslar uchun standart to'lov modeli, oylik hisob kuni, sababli dars krediti va boshqa to'lov qoidalari boshqariladi. Kurs formasida «To'lov modeli» maydoni paydo bo'ldi.",
    rollar: [1, 2],
    sahifa: { bolim: "tolovlar", sahifa: "tolov-turlari" },
  },
  {
    sana: "2026-09-19",
    sarlavha: "Bir odam ikki rolda — alohida hisob",
    matn: "O'quvchi hisobi xodim hisobi ochilishiga endi to'sqinlik qilmaydi: bir odam o'quvchi ham, xodim ham bo'lsa, unda ikkita alohida hisob va ikkita parol bo'ladi. Bitta telefonga bitta ishlab turgan xodim hisobi to'g'ri keladi.",
    rollar: [1, 2],
    sahifa: { bolim: "boshlash", sahifa: "tizimga-kirish" },
  },
  {
    sana: "2026-09-19",
    sarlavha: "Avtomatik pauza",
    matn: "Tizim ketma-ket sababsiz dars qoldirgan o'quvchini o'zi «Muzlatilgan» holatiga o'tkazishi mumkin; guruhdan chiqarmaydi. Sozlama boshida o'chiq: uni faqat CEO Sozlamalar → «Avtomatik pauza» da yoqadi. «Aloqa markazi»da «Pauzadagilar» tabi paydo bo'ldi, undagi «Faollashtirish» o'quvchini qaytaradi. Ogohlantirish va pauza haqida guruhning ustozlari va filial administratorlariga ham bildirishnoma keladi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "davomat", sahifa: "avtomatik-pauza" },
  },
  {
    sana: "2026-09-13",
    sarlavha: "Bot va mock imtihondan kelgan o'quvchi ham lid bilan yoziladi",
    matn: "Telegram bot orqali ro'yxatdan o'tgan va mock imtihon ishtirokchisidan aylantirilgan o'quvchi ham lid bilan bog'lanadi: mos lid bo'lmasa, yangi lidning manbasi «Telegram bot» yoki «Mock imtihon» bo'ladi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "oquvchilar", sahifa: "hayot-davri" },
  },
  {
    sana: "2026-09-10",
    sarlavha: "Faol o'quvchilar soni hamma joyda bir xil",
    matn: "Bosh sahifa, «O'quvchilar» sahifasi va Telegram hisobotida faol o'quvchi endi bir xil qoida bilan sanaladi: holati «Faol» va hozir faol guruhda o'qiydi.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "boshlash", sahifa: "lugat" },
  },
  {
    sana: "2026-09-10",
    sarlavha: "«Yangi o'quvchi» oynasida «Qayerdan bildi?» majburiy",
    matn: "Har yangi o'quvchi lid bilan bog'lanadi. Shuning uchun «O'quvchilar» sahifasidagi «Yangi o'quvchi» oynasida «Qayerdan bildi?» maydonini tanlash shart.",
    rollar: [1, 2, 3],
    sahifa: { bolim: "oquvchilar", sahifa: "yangi-oquvchi" },
  },
  {
    sana: "2026-09-02",
    sarlavha: "Kunlik jadval «Jadval» sahifasiga ko'chdi",
    matn: "Kunlik dars jadvali ilgari Bosh sahifaning o'zi edi; endi u chap menyudagi «Jadval» sahifasida (hamma xodim ko'radi). Bosh sahifada boshqaruv paneli turadi; jadvalni u yerda faqat o'qituvchi roli bor xodim ko'radi.",
    sahifa: { bolim: "guruhlar", sahifa: "jadval" },
  },
];
