import type { QollanmaSahifa } from "../turlar";

export const boshlash: QollanmaSahifa[] = [
  {
    bolim: "boshlash",
    sahifa: "tizimga-kirish",
    sarlavha: "Tizimga kirish va parol",
    qisqacha:
      "Tizimga telefon raqam va parol bilan kirasiz, xohlasangiz Telegram orqali ham. Parolni unutsangiz SMS kod yordam beradi; o'z parolingiz va telefoningizni Profilda o'zgartirasiz.",
    rollar: [1, 2, 3, 4, 5],
    adr: ["0022", "0030", "0031"],
    yollar: ["/profile"],
    kalitSozlar: [
      "kirish",
      "login",
      "parol",
      "parolni unutdim",
      "parolni tiklash",
      "SMS kod",
      "telefon raqam",
      "telefonni o'zgartirish",
      "Telegram orqali kirish",
      "profil",
      "boshqa qurilmalardan chiqish",
      "chiqish",
      "sessiya",
      "portal",
      "admin panel",
      "o'qituvchi portali",
    ],
    yangilangan: "2026-09-30",
  },
  {
    bolim: "boshlash",
    sahifa: "interfeys",
    sarlavha: "Ekran tuzilishi",
    qisqacha:
      "Chap menyu rolingizga qarab ochiladi. Yuqori panelda filial, qidiruv, soat, bildirishnomalar va shu sahifa bo'yicha qo'llanma tugmasi turadi.",
    rollar: [1, 2, 3, 4, 5],
    adr: [],
    yollar: ["/"],
    kalitSozlar: ["menyu", "filial", "qidiruv", "bildirishnoma", "mavzu", "profil", "chiqish"],
    yangilangan: "2026-09-30",
  },
  {
    bolim: "boshlash",
    sahifa: "rollar-va-huquqlar",
    sarlavha: "Rollar va huquqlar",
    qisqacha:
      "Tizimda beshta rol bor va har biri o'z ishini qiladi; filial direktori va administrator faqat o'z filialida ishlaydi. Rol berish, xodim hisobini o'zgartirish va bloklash qoidalari, kim nima qila olishi shu yerda.",
    rollar: [1, 2, 3, 4, 5],
    adr: ["0001", "0002", "0007", "0026", "0027", "0028"],
    yollar: [],
    kalitSozlar: [
      "rol",
      "huquq",
      "ruxsat",
      "CEO",
      "filial direktori",
      "direktor",
      "administrator",
      "o'qituvchi",
      "kassir",
      "lavozim",
      "filial chegarasi",
      "rol berish",
      "xodim hisobi",
      "bloklangan",
      "hisobingiz bloklangan",
      "to'xtatilgan",
      "ishdan bo'shatilgan",
    ],
    yangilangan: "2026-09-30",
  },
  {
    bolim: "boshlash",
    sahifa: "topshiriqlar",
    sarlavha: "Izohlar va topshiriqlar",
    qisqacha:
      "Izoh — yozuv, topshiriq — ijrochisi bor izoh. Topshiriqni ekranda CEO va filial direktori beradi; ijrochi uni «Ko'rdim» va «Bajarildi» deb belgilaydi.",
    rollar: [1, 2, 3, 4, 5],
    adr: [],
    yollar: ["/tasks"],
    kalitSozlar: [
      "izoh",
      "izohlar",
      "topshiriq",
      "vazifa",
      "muddat",
      "ko'rdim",
      "bajarildi",
      "kutilmoqda",
      "eslatma",
      "ijrochi",
      "menga berilgan",
      "men bergan",
      "ustuvorlik",
    ],
    yangilangan: "2026-09-30",
  },
  {
    bolim: "boshlash",
    sahifa: "lugat",
    sarlavha: "Lug'at",
    qisqacha:
      "Tizimda uchraydigan atamalar alifbo tartibida: rollar, o'quvchi va guruh holatlari, davomat, to'lov va oylik so'zlari bir-ikki gapda tushuntirilgan.",
    rollar: [1, 2, 3, 4, 5],
    adr: ["0015"],
    yollar: [],
    kalitSozlar: [
      "atama",
      "lug'at",
      "nima degani",
      "ta'rif",
      "faol o'quvchi",
      "balans",
      "qarz",
      "sikl",
      "stavka",
      "avans",
      "muzlatilgan",
      "chetlatilgan",
      "bitirgan",
      "keldi",
      "kelmadi",
      "kechikdi",
      "sababli",
    ],
    yangilangan: "2026-09-30",
  },
];
