import type { QollanmaSahifa } from "../turlar";

export const boshlash: QollanmaSahifa[] = [
  {
    bolim: "boshlash",
    sahifa: "tizimga-kirish",
    sarlavha: "Tizimga kirish va parol",
    qisqacha:
      "Tizimga telefon raqam va parol bilan kirasiz, xohlasangiz Telegram orqali ham; botdagi «Kabinet» tugmasi kabinetni parolsiz ochadi. Parolni unutsangiz SMS kod yordam beradi; o'z parolingiz va telefoningizni Profilda o'zgartirasiz.",
    rollar: [1, 2, 3, 4, 5],
    adr: ["0022", "0030", "0031", "0045", "0070"],
    yollar: ["/profile"],
    kalitSozlar: [
      "kirish",
      "login",
      "parol",
      "parolni unutdim",
      "parolni tiklash",
      "SMS kod",
      "telefon raqam",
      "telefonni o'zgartirish",
      "zaxira raqam",
      "Telegram orqali kirish",
      "xush kelibsiz",
      "daftar",
      "kabinet",
      "Telegram kabinet",
      "mini app",
      "Telegram bot",
      "xodim",
      "Telegramni bog'lash",
      "profil",
      "boshqa qurilmalardan chiqish",
      "chiqish",
      "sessiya",
      "portal",
      "admin panel",
      "o'qituvchi portali",
    ],
    yangilangan: "2026-10-03",
  },
  {
    bolim: "boshlash",
    sahifa: "interfeys",
    sarlavha: "Ekran tuzilishi",
    qisqacha:
      "Chap menyu rolingizga qarab ochiladi. Yuqori panelda filial, qidiruv, soat, bildirishnomalar va shu sahifa bo'yicha qo'llanma tugmasi turadi.",
    rollar: [1, 2, 3, 4, 5],
    adr: [],
    yollar: ["/"],
    kalitSozlar: ["menyu", "filial", "qidiruv", "bildirishnoma", "mavzu", "profil", "chiqish"],
    yangilangan: "2026-10-02",
  },
  {
    bolim: "boshlash",
    sahifa: "rollar-va-huquqlar",
    sarlavha: "Rollar va huquqlar",
    qisqacha:
      "Tizimda beshta rol bor va har biri o'z ishini qiladi; filial direktori va administrator faqat o'z filialida ishlaydi. Rol berish, xodim hisobini o'zgartirish va bloklash qoidalari, kim nima qila olishi shu yerda.",
    rollar: [1, 2, 3, 4, 5],
    adr: ["0001", "0002", "0007", "0026", "0027", "0028", "0054", "0063"],
    yollar: [],
    kalitSozlar: [
      "rol",
      "huquq",
      "ruxsat",
      "CEO",
      "filial direktori",
      "direktor",
      "administrator",
      "o'qituvchi",
      "kassir",
      "lavozim",
      "filial chegarasi",
      "boshqa filialda",
      "rol berish",
      "xodim hisobi",
      "bloklangan",
      "hisobingiz bloklangan",
      "to'xtatilgan",
      "ishdan bo'shatilgan",
      "dars bo'ldimi",
      "ustoz aybdor emas",
      "guruhlar kassirga ko'rinmaydi",
      "davomat ochilish vaqti",
    ],
    yangilangan: "2026-10-03",
  },
  {
    bolim: "boshlash",
    sahifa: "topshiriqlar",
    sarlavha: "Izohlar va topshiriqlar",
    qisqacha:
      "Izoh — yozuv, topshiriq — ijrochisi bor izoh. Topshiriqni «Topshiriq» kaliti bilan CEO va filial direktori beradi, ijrochi uni «Ko'rdim» va «Bajarildi» deb belgilaydi; davomat olinmagan darsda administratorga tizim «Dars bo'ldimi?» topshirig'ini beradi.",
    rollar: [1, 2, 3, 4, 5],
    adr: ["0054", "0063"],
    yollar: ["/tasks"],
    kalitSozlar: [
      "izoh",
      "izohlar",
      "topshiriq",
      "vazifa",
      "muddat",
      "ko'rdim",
      "bajarildi",
      "kutilmoqda",
      "eslatma",
      "ijrochi",
      "menga berilgan",
      "men bergan",
      "ustuvorlik",
      "dars bo'ldimi",
      "tizim topshirig'i",
      "bo'ldi",
      "bo'lmadi",
      "davomat olinmadi",
    ],
    yangilangan: "2026-10-03",
  },
  {
    bolim: "boshlash",
    sahifa: "lugat",
    sarlavha: "Lug'at",
    qisqacha:
      "Tizimda uchraydigan atamalar alifbo tartibida: rollar, o'quvchi va guruh holatlari, davomat, qarz, to'lov va oylik so'zlari bir-ikki gapda tushuntirilgan.",
    rollar: [1, 2, 3, 4, 5],
    adr: ["0015", "0047", "0048", "0054", "0055", "0058", "0059", "0060", "0062", "0064", "0065", "0066"],
    yollar: [],
    kalitSozlar: [
      "atama",
      "lug'at",
      "nima degani",
      "ta'rif",
      "faol o'quvchi",
      "balans",
      "qarz",
      "sikl",
      "stavka",
      "avans",
      "muzlatilgan",
      "chetlatilgan",
      "bitirgan",
      "keldi",
      "kelmadi",
      "kechikdi",
      "sababli",
      "dars bo'ldimi",
      "berilmadi",
      "darsga qo'yilmaydi",
      "sinov darsi",
      "hisoblandi",
      "to'landi",
      "qoldi",
      "o'qiyotganlar qarzi",
      "o'qimayotganlar qarzi",
      "yechib olish",
      "sof foyda",
      "eng kam to'lov",
      "50%",
      "oylik",
      "to'lov cheki",
      "chek",
      "telegram uzilgan",
      "telegram kabinet",
      "bot bloklangan",
    ],
    yangilangan: "2026-10-03",
  },
];
