import type { QollanmaSahifa } from "../turlar";

export const davomat: QollanmaSahifa[] = [
  {
    bolim: "davomat",
    sahifa: "davomat-olish",
    sarlavha: "Davomat olish",
    qisqacha:
      "Davomatni guruh sahifasining «Davomat» tabida olasiz: har o'quvchiga «Keldi», «Kelmadi», «Kechikdi» yoki «Sababli» qo'yiladi, hammasi belgilanmaguncha saqlanmaydi. O'qituvchi faqat bugungi darsni, dars boshlanishidan 10 daqiqa oldin to tugaguncha oladi; administrator istalgan dars kunini.",
    rollar: [1, 2, 3, 4],
    adr: [],
    yollar: ["/groups/*"],
    kalitSozlar: [
      "davomat",
      "davomat olish",
      "davomat belgilash",
      "keldi",
      "kelmadi",
      "kechikdi",
      "sababli",
      "belgilanmagan",
      "saqlash",
      "barchasiga keldi",
      "QR davomat",
      "QR kod",
      "skanerlash",
      "davomat olib bo'lingan",
      "davomatni tuzatish",
      "davomatni tiklash",
      "o'qituvchi davomati",
      "dars vaqti",
      "10 daqiqa oldin",
      "olinmagan darslar",
      "qarzdor o'quvchi",
      "qarz belgisi",
      "ustozga ulush",
      "davomat tarixi",
    ],
    yangilangan: "2026-09-30",
  },
  {
    bolim: "davomat",
    sahifa: "oldindan-belgilash",
    sarlavha: "Oldindan belgilash",
    qisqacha:
      "O'quvchi darsga kelmasligini oldindan aytsa, CEO, direktor yoki administrator uni davomat olinmasidan oldin «Sababli» (sabab yozish majburiy) yoki «Kelmaydi» (sababsiz) deb belgilab qo'yadi. Bu davomat emas: pul yechilmaydi, davomat olinganda o'quvchi «Sababli» bo'lib turadi; sababsiz kelmaslik avtomatik pauza sanog'iga kiradi.",
    rollar: [1, 2, 3],
    adr: [],
    yollar: ["/groups/*"],
    kalitSozlar: [
      "oldindan belgilash",
      "oldindan davomat",
      "oldindan aytgan",
      "bugun kelmaydi",
      "kelmaydi",
      "sababli",
      "sababsiz",
      "sabab yozish",
      "oldindan belgilash rejimi",
      "hozir to'liq davomat olish",
      "belgini o'chirish",
      "telefon qildi",
      "kasal",
      "pul yechilmaydi",
      "avtomatik pauza zanjiri",
    ],
    yangilangan: "2026-09-30",
  },
  {
    bolim: "davomat",
    sahifa: "avtomatik-pauza",
    sarlavha: "Avtomatik pauza",
    qisqacha:
      "Yoqilgan bo'lsa, tizim ketma-ket 3 ta (boshlang'ich qiymat) sababsiz dars qoldirgan o'quvchini ertasi ertalab 07:30 da «Muzlatilgan» qiladi, guruhdan chiqarmaydi; undan oldin 20:30 da o'quvchiga Telegramda xabar boradi. Sozlamani faqat CEO yoqadi, boshida o'chiq; kunlik chegara oshsa hech kim to'xtatilmaydi.",
    rollar: [1, 2, 3],
    adr: ["0023"],
    yollar: ["/outreach", "/settings/absence-pause"],
    kalitSozlar: [
      "avtomatik pauza",
      "pauza",
      "pauzaga tushdi",
      "pauzadagilar",
      "faollashtirish",
      "ketma-ket kelmagan",
      "ketma-ket dars qoldirish",
      "uchta dars",
      "3 ta dars",
      "sanoq",
      "zanjir",
      "ogohlantirish",
      "eslatma",
      "kunlik chegara",
      "bir kunda ko'pi bilan",
      "chegara oshdi",
      "aloqa markazi",
      "ko'p dars qoldirganlar",
      "pauza yoqasida",
      "muzlatilgan",
      "20:30",
      "07:30",
    ],
    yangilangan: "2026-09-30",
  },
  {
    bolim: "davomat",
    sahifa: "eslatmalar",
    sarlavha: "Davomat eslatmalari",
    qisqacha:
      "Tizim o'qituvchiga dars boshlanganda eslatadi; davomat olinmasa, dars tugashiga 30 daqiqa qolganda o'qituvchi va filial administratorlariga, dars tugaganda yana ikkalasiga xabar beradi. Davomat birinchi marta saqlanganda o'qituvchiga statistika keladi; yakshanba va bayram kunlari eslatma yo'q.",
    rollar: [1, 2, 3, 4],
    adr: [],
    yollar: [],
    kalitSozlar: [
      "davomat eslatmasi",
      "eslatma",
      "bildirishnoma",
      "dars boshlandi",
      "davomat belgilanmadi",
      "o'qituvchiga eslatib qo'ying",
      "davomat qabul qilindi",
      "statistika xabari",
      "30 daqiqa qoldi",
      "dars tugadi",
      "yakshanba",
      "bayram",
      "Telegram",
      "push",
      "kim oladi",
      "davomatni tiklash",
    ],
    yangilangan: "2026-09-30",
  },
];
