import type { QollanmaSahifa } from "../turlar";

export const davomat: QollanmaSahifa[] = [
  {
    bolim: "davomat",
    sahifa: "davomat-olish",
    sarlavha: "Davomat olish",
    qisqacha:
      "Davomatni guruh sahifasining «Davomat» tabida olasiz: har o'quvchiga «Keldi», «Kelmadi», «Kechikdi» yoki «Sababli» qo'yiladi. Yangi davomat hamma rol uchun faqat dars kuni, dars boshlanishidan 10 daqiqa oldin (boshlang'ich qiymat) to dars tugaguncha ochiq; saqlangan davomatni administrator keyin ham tuzatadi.",
    rollar: [1, 2, 3, 4],
    adr: ["0047", "0048", "0054", "0064"],
    yollar: ["/groups/*"],
    kalitSozlar: [
      "davomat",
      "davomat olish",
      "davomat belgilash",
      "keldi",
      "kelmadi",
      "kechikdi",
      "sababli",
      "belgilanmagan",
      "saqlash",
      "barchasiga keldi",
      "QR davomat",
      "QR kod",
      "skanerlash",
      "davomat olib bo'lingan",
      "davomatni tuzatish",
      "davomatni tiklash",
      "o'qituvchi davomati",
      "dars vaqti",
      "10 daqiqa oldin",
      "olinmagan darslar",
      "ustozga ulush",
      "davomat tarixi",
      "davomat oynasi",
      "davomat ochilish vaqti",
      "dars tugagan",
      "kechikish daqiqasi",
    ],
    yangilangan: "2026-10-03",
  },
  {
    bolim: "davomat",
    sahifa: "darsga-qoyish",
    sarlavha: "To'lamagan o'quvchi darsga qo'yilmaydi",
    qisqacha:
      "Oylik kursda o'quvchi oyning o'zining 1-darsiga to'lovsiz keladi. 2-darsdan boshlab puli shu darsgacha yetmasa — va 01.11.2026 dan oy to'lovining kamida 50% i (har guruhda alohida) to'lanmagan bo'lsa — unga «Keldi», «Kelmadi» va «Kechikdi» qo'yib bo'lmaydi, faqat «Sababli»; administrator qatorning o'zida «To'lov qabul qilish» ni bosadi, qoidani CEO sozlamadan o'zgartiradi.",
    rollar: [1, 2, 3, 4],
    adr: ["0047", "0062", "0064"],
    yollar: ["/groups/*"],
    kalitSozlar: [
      "darsga qo'yilmaydi",
      "darsga qo'yilmaslik",
      "to'lov qilinmagan",
      "to'lamagan o'quvchi",
      "2-dars",
      "oyning 1-darsi",
      "shartnoma 3.2",
      "qarzdor o'quvchi",
      "qarz belgisi",
      "qarzdorlar paneli",
      "to'lov qabul qilish",
      "dars vaqtida davomatga kiritilmagan",
      "qisman to'lagan",
      "eng kam to'lov",
      "kamida 50%",
      "oy to'lovining yarmi",
      "darsga kirish uchun eng kam to'lov",
      "shu oy ustuni",
    ],
    yangilangan: "2026-10-03",
  },
  {
    bolim: "davomat",
    sahifa: "dars-boldimi",
    sarlavha: "Dars bo'ldimi? — olinmagan dars",
    qisqacha:
      "Dars tugaguncha davomat olinmasa, filial administratorlariga «Dars bo'ldimi?» savoli va topshiriq keladi. «Bo'ldi» — davomat kech kiritiladi va ustozga bu dars uchun haq yozilmaydi (faqat CEO istisno qiladi), «Bo'lmadi» — dars bekor qilinadi yoki ko'chiriladi.",
    rollar: [1, 2, 3],
    adr: ["0048", "0054", "0060"],
    yollar: ["/schedule", "/tasks", "/groups/*"],
    kalitSozlar: [
      "dars bo'ldimi",
      "bo'ldi",
      "bo'lmadi",
      "davomat olinmadi",
      "olinmagan dars",
      "javobsiz dars",
      "berilmadi",
      "ustoz haqi yozilmadi",
      "ustoz aybdor emas",
      "haq yozilsin",
      "tizim topshirig'i",
      "davomatni kech kiritish",
      "javob bermoqda",
    ],
    yangilangan: "2026-10-03",
  },
  {
    bolim: "davomat",
    sahifa: "oldindan-belgilash",
    sarlavha: "Oldindan belgilash",
    qisqacha:
      "O'quvchi darsga kelmasligini oldindan aytsa, CEO, direktor yoki administrator uni dars tugaguncha «Sababli» (sabab yozish majburiy) yoki «Kelmaydi» (sababsiz) deb belgilab qo'yadi. Bu davomat emas: pul yechilmaydi, davomat olinganda o'quvchi «Sababli» bo'lib turadi; sababsiz kelmaslik avtomatik pauza sanog'iga kiradi.",
    rollar: [1, 2, 3],
    adr: ["0047", "0054"],
    yollar: ["/groups/*"],
    kalitSozlar: [
      "oldindan belgilash",
      "oldindan davomat",
      "oldindan aytgan",
      "bugun kelmaydi",
      "kelmaydi",
      "sababli",
      "sababsiz",
      "sabab yozish",
      "oldindan belgilash rejimi",
      "hozir to'liq davomat olish",
      "belgini o'chirish",
      "telefon qildi",
      "kasal",
      "pul yechilmaydi",
      "avtomatik pauza zanjiri",
      "dars tugaguncha",
    ],
    yangilangan: "2026-10-03",
  },
  {
    bolim: "davomat",
    sahifa: "avtomatik-pauza",
    sarlavha: "Avtomatik pauza",
    qisqacha:
      "Yoqilgan bo'lsa, tizim ketma-ket 3 ta (boshlang'ich qiymat) sababsiz dars qoldirgan o'quvchini ertasi ertalab 07:30 da «Muzlatilgan» qiladi, guruhdan chiqarmaydi; undan oldin 20:30 da o'quvchiga Telegramda xabar boradi. Sozlamani faqat CEO yoqadi, boshida o'chiq; kunlik chegara oshsa hech kim to'xtatilmaydi.",
    rollar: [1, 2, 3],
    adr: ["0023", "0054", "0066"],
    yollar: ["/outreach", "/settings/absence-pause"],
    kalitSozlar: [
      "avtomatik pauza",
      "pauza",
      "pauzaga tushdi",
      "pauzadagilar",
      "faollashtirish",
      "ketma-ket kelmagan",
      "ketma-ket dars qoldirish",
      "uchta dars",
      "3 ta dars",
      "sanoq",
      "zanjir",
      "ogohlantirish",
      "eslatma",
      "kunlik chegara",
      "bir kunda ko'pi bilan",
      "chegara oshdi",
      "aloqa markazi",
      "ko'p dars qoldirganlar",
      "pauza yoqasida",
      "muzlatilgan",
      "20:30",
      "07:30",
      "telegram uzilgan",
    ],
    yangilangan: "2026-10-03",
  },
  {
    bolim: "davomat",
    sahifa: "eslatmalar",
    sarlavha: "Davomat eslatmalari",
    qisqacha:
      "Tizim o'qituvchiga dars boshlanganda eslatadi; davomat olinmasa, dars tugashiga 30 daqiqa qolganda o'qituvchi va filial administratorlariga xabar beradi. Dars tugab davomat olinmagan bo'lsa, ikkalasiga «Davomat olinmadi» boradi va administrator «Dars bo'ldimi?» topshirig'ini oladi; davomat birinchi marta saqlanganda o'qituvchiga statistika keladi.",
    rollar: [1, 2, 3, 4],
    adr: ["0047", "0054"],
    yollar: [],
    kalitSozlar: [
      "davomat eslatmasi",
      "eslatma",
      "bildirishnoma",
      "dars boshlandi",
      "davomat qabul qilindi",
      "statistika xabari",
      "30 daqiqa qoldi",
      "dars tugadi",
      "yakshanba",
      "bayram",
      "Telegram",
      "push",
      "kim oladi",
      "davomatni tiklash",
      "davomat olinmadi",
      "dars bo'ldimi",
      "o'qituvchi hali davomat olmadi",
      "dars haqi yozilmadi",
      "ustozga haq yozilmaydi",
    ],
    yangilangan: "2026-10-02",
  },
];
