import type { QollanmaSahifa } from "../turlar";

export const guruhlar: QollanmaSahifa[] = [
  {
    bolim: "guruhlar",
    sahifa: "guruh-yaratish",
    sarlavha: "Guruh yaratish",
    qisqacha:
      "Guruh «Guruhlar» sahifasida «Yangi guruh» tugmasi bilan ochiladi: daraja, kurs, dars kunlari va boshlanish vaqti majburiy. Kurs, xona va ustoz guruh filialidan tanlanadi, ustozda ish haqi stavkasi bo'lishi shart va filial keyin o'zgarmaydi; guruh «Boshlanmagan» bo'lib ochiladi va boshlanish sanasida o'zi «Faol» bo'ladi.",
    rollar: [1, 2, 3],
    adr: [],
    yollar: ["/groups"],
    kalitSozlar: [
      "guruh yaratish",
      "yangi guruh",
      "guruh ochish",
      "guruh qo'shish",
      "guruh nomi",
      "avtomatik nom",
      "daraja",
      "kurs",
      "dars kunlari",
      "toq kunlar",
      "juft kunlar",
      "har kun",
      "dars vaqti",
      "dars davomiyligi",
      "xona band",
      "ustoz band",
      "ustoz tanlash",
      "ish haqi stavkasi belgilanmagan",
      "stavka",
      "boshlanish sanasi",
      "tugash sanasi",
      "filial",
      "guruhni tahrirlash",
      "ustoz almashtirish",
      "ustoz o'zgarishi",
      "QR kod",
      "guruh havolasi",
      "kassir guruhlar",
    ],
    yangilangan: "2026-10-03",
  },
  {
    bolim: "guruhlar",
    sahifa: "guruh-holatlari",
    sarlavha: "Guruh holatlari",
    qisqacha:
      "Guruh «Boshlanmagan» bo'lib ochiladi, «Faol» bo'ladi, keyin «Pauza»ga tushishi, «Tugallangan» yoki «Bekor qilingan» bo'lishi mumkin; oxirgi ikki holatdan qaytish yo'q. Tugallanganda faol o'quvchilar bitiradi, muzlatilganlar chiqariladi; bekor qilinganda hammasi chiqariladi, pul balansga qaytadi; o'zgarish yo to'liq bajariladi, yo umuman.",
    rollar: [1, 2, 3],
    adr: ["0036", "0041"],
    yollar: ["/groups/*"],
    kalitSozlar: [
      "guruh holati",
      "status",
      "status o'zgartirish",
      "status tarixi",
      "boshlanmagan",
      "faol",
      "pauza",
      "tugallangan",
      "yakunlangan",
      "bekor qilingan",
      "to'xtatilgan",
      "arxivlangan",
      "guruhni yopish",
      "guruhni yakunlash",
      "guruhni bekor qilish",
      "guruhni o'chirish",
      "guruhni tiklash",
      "bitirish",
      "avtomatik bitirish",
      "muzlatilgan o'quvchi",
      "guruh tugash sanasi",
      "hech narsa saqlanmadi",
      "qayta urinib ko'ring",
      "filial yopilsa",
      "arxivdan tiklash",
    ],
    yangilangan: "2026-10-03",
  },
  {
    bolim: "guruhlar",
    sahifa: "dars-ozgarishlari",
    sarlavha: "Darsni bekor qilish, ko'chirish, o'rinbosar",
    qisqacha:
      "Guruh sahifasining «Dars o'zgarishlari» tabida darsni bekor qilasiz, boshqa kunga ko'chirasiz yoki bir kunga o'rinbosar ustoz qo'yasiz. Bekor qilinganda shu kungi davomat belgilari «Sababli» ga o'tadi va oylik to'lovchiga bir dars puli darhol qaytadi; bekor qilish yozuvini o'chirsangiz qaytgan pul qayta yechiladi, davomat esa tiklanmaydi.",
    rollar: [1, 2, 3],
    adr: ["0048", "0053", "0054", "0063"],
    yollar: ["/groups/*"],
    kalitSozlar: [
      "darsni bekor qilish",
      "dars bekor",
      "bekor qilingan dars",
      "darsni ko'chirish",
      "boshqa kunga ko'chirish",
      "ko'chirilgan dars",
      "ko'chirib kelingan",
      "o'rinbosar",
      "o'rinbosar ustoz",
      "ustoz kasal",
      "dars o'zgarishlari",
      "sababli",
      "uzrli",
      "pul qaytadi",
      "yozuvni o'chirish",
      "xona band",
      "ko'chirishni tahrirlash",
      "ustoz oyligi qayta hisoblanadi",
      "dars puli qaytadi",
      "o'rinbosarga haq yozilmaydi",
      "qarzdorning birinchi darsi",
      "sinov darsi",
      "o'rinbosar stavka",
      "bekor qilishni o'chirish",
    ],
    yangilangan: "2026-10-03",
  },
  {
    bolim: "guruhlar",
    sahifa: "bayramlar",
    sarlavha: "Bayramlar",
    qisqacha:
      "Bayram Sozlamalar → «Dam olish kunlari» da butun markaz uchun kiritiladi: shu kunlarda davomat olinmaydi, dars eslatmalari va Telegram guruh hisobotlari ketmaydi. Tugash sanasi bor «Faol» va «Boshlanmagan» guruhlarning tugash sanasi bayramga tushgan dars kunlariga suriladi.",
    rollar: [1, 2, 3],
    adr: [],
    yollar: ["/settings/holidays"],
    kalitSozlar: [
      "bayram",
      "dam olish kunlari",
      "dam olish kuni",
      "yangi bayram",
      "bayram qo'shish",
      "bayram o'chirish",
      "bir necha kunlik bayram",
      "Navro'z",
      "Mustaqillik kuni",
      "guruh tugash sanasi",
      "tugash sanasi suriladi",
      "davomat olinmaydi",
      "bayram kuni",
      "60 kun",
      "yakshanba",
      "Telegram hisobot",
    ],
    yangilangan: "2026-10-03",
  },
  {
    bolim: "guruhlar",
    sahifa: "jadval",
    sarlavha: "Jadval",
    qisqacha:
      "«Jadval» tanlangan kun va filial uchun guruhlarning darslarini xonalar bo'yicha «Grid»da yoki «Ro'yxat»da ko'rsatadi; o'qituvchiga faqat o'z darslari ko'rsatiladi. Jadval bekor qilingan va ko'chirilgan darsni hamda o'rinbosar ustozni hisobga olmaydi.",
    rollar: [1, 2, 3, 4, 5],
    adr: [],
    yollar: ["/schedule"],
    kalitSozlar: [
      "jadval",
      "kunlik jadval",
      "dars jadvali",
      "bugungi darslar",
      "grid",
      "ro'yxat",
      "xona bandligi",
      "xonalar",
      "band xonalar",
      "darslarim",
      "o'quvchilarim",
      "davomat olindi",
      "davomat olinmagan",
      "o'tkazib yuborilgan",
      "dam olish kuni",
      "filial tanlang",
      "bugunga qaytish",
    ],
    yangilangan: "2026-10-03",
  },
];
