import type { QollanmaSahifa } from "../turlar";

export const oquvchilar: QollanmaSahifa[] = [
  {
    bolim: "oquvchilar",
    sahifa: "hayot-davri",
    sarlavha: "O'quvchining hayot davri",
    qisqacha:
      "O'quvchi lid bo'lib boshlanadi, keyin «Faol» bo'ladi; muzlatilishi, chetlatilishi, bitirishi yoki arxivga tushishi mumkin. Har holat va o'tish diagrammada ko'rsatilgan, «faol o'quvchi» hisobotlarda nimani bildirishi ham yozilgan.",
    rollar: [1, 2, 3],
    adr: ["0015", "0017", "0018"],
    yollar: ["/students"],
    kalitSozlar: [
      "hayot davri",
      "holat",
      "status",
      "lid",
      "o'quvchiga aylantirish",
      "faol",
      "faol o'quvchi",
      "aktiv o'quvchilar",
      "guruhlashtirilmagan",
      "guruhsiz",
      "muzlatilgan",
      "chetlatilgan",
      "bitirgan",
      "arxivlangan",
      "ketgan o'quvchi",
      "qayerdan bildi",
      "manba",
    ],
    yangilangan: "2026-09-30",
  },
  {
    bolim: "oquvchilar",
    sahifa: "yangi-oquvchi",
    sarlavha: "Yangi o'quvchi",
    qisqacha:
      "Yangi o'quvchi «O'quvchilar» sahifasida qo'lda yoki Telegram havolasi orqali qo'shiladi. Filial majburiy va bitta; telefon raqam o'quvchining kirish raqami, kartada o'zgarsa kirish ham o'zgaradi.",
    rollar: [1, 2, 3],
    adr: ["0032", "0039"],
    yollar: ["/students"],
    kalitSozlar: [
      "yangi o'quvchi",
      "o'quvchi qo'shish",
      "ro'yxatdan o'tkazish",
      "qayerdan bildi",
      "manba",
      "telefon raqam",
      "kirish raqami",
      "login",
      "parol",
      "yangi parol",
      "havola olish",
      "telegram havola",
      "telegram orqali ro'yxatdan o'tish",
      "telefon tasdiqlangan",
      "telefon tasdiqlanmagan",
      "jins",
      "tug'ilgan sana",
      "birinchi kirish",
      "filial",
    ],
    yangilangan: "2026-09-30",
  },
  {
    bolim: "oquvchilar",
    sahifa: "oquvchi-kartasi",
    sarlavha: "O'quvchi kartasi",
    qisqacha:
      "Karta chapda o'quvchi ma'lumotlari, balans va amallarni, o'ngda 10 ta tabni ko'rsatadi. «To'lovlar» tabi o'quvchi qancha to'lagani, pul qaysi darslarga ketgani va balans nimadan chiqqanini tushuntiradi.",
    rollar: [1, 2, 3],
    adr: ["0004", "0037"],
    yollar: ["/students/profile/*"],
    kalitSozlar: [
      "o'quvchi kartasi",
      "profil",
      "tab",
      "guruhlar",
      "to'lovlar",
      "to'lovlar hisoboti",
      "oylar bo'yicha",
      "to'lovlar qayerga ketdi",
      "pdf yuklab olish",
      "balans",
      "qarz",
      "darslar",
      "izohlar",
      "qo'ng'iroq tarixi",
      "sms",
      "tarix",
      "status tarixi",
      "lid tarixi",
      "mock imtihonlar",
      "ilova",
      "tahrirlash",
      "chegirma",
      "yangi parol",
    ],
    yangilangan: "2026-09-30",
  },
  {
    bolim: "oquvchilar",
    sahifa: "guruhga-qoshish",
    sarlavha: "Guruhga qo'shish va o'tkazish",
    qisqacha:
      "O'quvchi bir vaqtda bitta faol guruhda o'qiydi va faqat o'z filialidagi guruhga qo'shiladi. Oylik kursda oy o'rtasida qo'shilsa qolgan darslar puli olinadi; boshqa guruhga o'tkazilsa eski oyning o'tilmagan darslar puli qaytadi.",
    rollar: [1, 2, 3],
    adr: [],
    yollar: ["/students/profile/*"],
    kalitSozlar: [
      "guruhga qo'shish",
      "guruhga biriktirish",
      "guruhni o'zgartirish",
      "o'tkazish",
      "boshqa guruhga o'tkazish",
      "guruh almashtirish",
      "transfer sababi",
      "ustoz farqli",
      "boshlanish sanasi",
      "oy o'rtasida qo'shilish",
      "yozilish",
    ],
    yangilangan: "2026-09-30",
  },
  {
    bolim: "oquvchilar",
    sahifa: "muzlatish",
    sarlavha: "Muzlatish va qaytarish",
    qisqacha:
      "Muzlatilgan o'quvchi davomatdan chiqadi, undan dars puli yechilmaydi va oyning o'tilmagan darslar puli balansga qaytadi. Qaytganda oylik kursda faqat qaytgan kundan keyingi darslar hisoblanadi.",
    rollar: [1, 2, 3],
    adr: [],
    yollar: ["/students/profile/*"],
    kalitSozlar: [
      "muzlatish",
      "muzlatilgan",
      "qaytarish",
      "faollashtirish",
      "pauza",
      "avtomatik pauza",
      "status o'zgartirish",
      "davomatdan chiqadi",
      "muzlatilgan puli",
      "qaytgan kun",
    ],
    yangilangan: "2026-09-30",
  },
  {
    bolim: "oquvchilar",
    sahifa: "guruhdan-chiqarish",
    sarlavha: "Guruhdan chiqarish va pul",
    qisqacha:
      "Guruhdan chiqarishda pulni qaytarish tartibi tanlanadi. 01.10.2026 dan o'quvchi o'zi to'xtatsa va oyning 40% idan ko'pi o'tgan bo'lsa, oylik puli qaytmaydi; qaytgan pul balansga tushadi, naqd berilmaydi.",
    rollar: [1, 2, 3],
    adr: ["0043", "0044"],
    yollar: ["/students/profile/*"],
    kalitSozlar: [
      "guruhdan chiqarish",
      "chiqarish",
      "pul qaytarish",
      "pulni qaytarish tartibi",
      "pul (shartnoma bo'yicha)",
      "shartnoma 6.2",
      "6.2",
      "40%",
      "o'quvchi o'zi to'xtatdi",
      "darajani tugatdi",
      "markaz tashabbusi",
      "sifat bo'yicha shikoyat",
      "pul qaytmaydi",
      "qaytadigan dars yo'q",
      "ketish sababi",
    ],
    yangilangan: "2026-09-30",
  },
  {
    bolim: "oquvchilar",
    sahifa: "chetlatish-va-arxiv",
    sarlavha: "Chetlatish, bitirish, arxiv",
    qisqacha:
      "Chetlatilgan o'quvchining qarzi qoladi va u portal orqali to'lay oladi; bitirish guruh tugaganda o'zi bo'ladi. Arxiv faqat xato yoki takroriy yozuv uchun: kirish hisobi yopiladi, tiklashni faqat CEO qiladi.",
    rollar: [1, 2, 3],
    adr: ["0033"],
    yollar: ["/students/profile/*"],
    kalitSozlar: [
      "chetlatish",
      "chetlatilgan",
      "bitirish",
      "bitirgan",
      "arxiv",
      "arxivga o'tkazish",
      "arxivlash",
      "o'chirish",
      "qayta tiklash",
      "tiklash",
      "dublikat",
      "duplikat",
      "xato yozuv",
      "kirish hisobi yopiladi",
    ],
    yangilangan: "2026-09-30",
  },
];
