import type { QollanmaSahifa } from "../turlar";

export const oquvchilar: QollanmaSahifa[] = [
  {
    bolim: "oquvchilar",
    sahifa: "hayot-davri",
    sarlavha: "O'quvchining hayot davri",
    qisqacha:
      "O'quvchi lid bo'lib boshlanadi, keyin «Faol» bo'ladi; muzlatilishi, chetlatilishi, bitirishi yoki arxivga tushishi mumkin. Har holat va o'tish diagrammada ko'rsatilgan, faol o'quvchi hisobotlarda nimani bildirishi va qarz ikki raqamga qanday bo'linishi ham yozilgan.",
    rollar: [1, 2, 3],
    adr: ["0015", "0017", "0018", "0059"],
    yollar: ["/students"],
    kalitSozlar: [
      "hayot davri",
      "holat",
      "status",
      "lid",
      "o'quvchiga aylantirish",
      "faol",
      "faol o'quvchi",
      "aktiv o'quvchilar",
      "guruhlashtirilmagan",
      "guruhsiz",
      "muzlatilgan",
      "chetlatilgan",
      "bitirgan",
      "arxivlangan",
      "ketgan o'quvchi",
      "qayerdan bildi",
      "manba",
      "o'qiyotganlar qarzi",
      "o'qimayotganlar qarzi",
      "qarz ikki raqam",
    ],
    yangilangan: "2026-10-02",
  },
  {
    bolim: "oquvchilar",
    sahifa: "yangi-oquvchi",
    sarlavha: "Yangi o'quvchi",
    qisqacha:
      "Yangi o'quvchi «O'quvchilar» sahifasida qo'lda yoki Telegram havolasi orqali qo'shiladi. Filial majburiy va bitta; telefon raqam o'quvchining kirish raqami, kartada o'zgarsa kirish ham o'zgaradi; zaxira raqam bilan ham kiradi. Bot xabarlari yetib bormasa, kartada «Telegram uzilgan» belgisi chiqadi.",
    rollar: [1, 2, 3],
    adr: ["0032", "0039", "0066", "0070"],
    yollar: ["/students"],
    kalitSozlar: [
      "yangi o'quvchi",
      "o'quvchi qo'shish",
      "ro'yxatdan o'tkazish",
      "qayerdan bildi",
      "manba",
      "telefon raqam",
      "kirish raqami",
      "zaxira raqam",
      "login",
      "parol",
      "yangi parol",
      "havola olish",
      "telegram havola",
      "telegram orqali ro'yxatdan o'tish",
      "telefon tasdiqlangan",
      "telefon tasdiqlanmagan",
      "telegram uzilgan",
      "botni bloklagan",
      "telegram qayta ulandi",
      "jins",
      "tug'ilgan sana",
      "birinchi kirish",
      "filial",
    ],
    yangilangan: "2026-10-03",
  },
  {
    bolim: "oquvchilar",
    sahifa: "oquvchi-kartasi",
    sarlavha: "O'quvchi kartasi",
    qisqacha:
      "Karta chapda o'quvchi ma'lumotlari, balans va amallarni, o'ngda 11 ta tabni ko'rsatadi. «To'lovlar» tabi o'quvchi qancha to'lagani, har oyning narxi, to'langani va qarzi hamda balans nimadan chiqqanini tushuntiradi.",
    rollar: [1, 2, 3],
    adr: ["0004", "0037", "0047", "0062", "0064", "0066", "0070", "0073"],
    yollar: ["/students/profile/*"],
    kalitSozlar: [
      "o'quvchi kartasi",
      "profil",
      "zaxira raqam",
      "ota-ona raqami",
      "tab",
      "guruhlar",
      "to'lovlar",
      "to'lovlar hisoboti",
      "oylar bo'yicha",
      "qaysi oyga yozildi",
      "to'lovlar jadvali",
      "summani to'g'rilash",
      "chek",
      "pdf yuklab olish",
      "balans",
      "boshlang'ich balans",
      "boshqa filialda",
      "qarz",
      "darslar",
      "izohlar",
      "qo'ng'iroq tarixi",
      "sms",
      "tarix",
      "status tarixi",
      "lid tarixi",
      "mock imtihonlar",
      "ilova",
      "tahrirlash",
      "chegirma",
      "yangi parol",
      "kassir",
      "oy bloki",
      "yopilgan guruhlar",
      "uzrli dars",
      "telegram uzilgan",
      "id",
      "o'quvchi raqami",
      "barcha yozuvlar",
      "bekor qilingan yozuv",
      "balans tarixi",
    ],
    yangilangan: "2026-10-10",
  },
  {
    bolim: "oquvchilar",
    sahifa: "guruhga-qoshish",
    sarlavha: "Guruhga qo'shish va o'tkazish",
    qisqacha:
      "O'quvchi bir vaqtda bitta faol guruhda o'qiydi va faqat o'z filialidagi guruhga qo'shiladi. Oyna pulni oldindan ko'rsatadi: oylik kursda oy o'rtasida qo'shilsa qolgan darslar puli olinadi, boshqa guruhga o'tkazilsa eski oyning o'tilmagan darslar puli qaytadi.",
    rollar: [1, 2, 3],
    adr: ["0043", "0047", "0048", "0064"],
    yollar: ["/students/profile/*"],
    kalitSozlar: [
      "guruhga qo'shish",
      "guruhga biriktirish",
      "guruhni o'zgartirish",
      "o'tkazish",
      "boshqa guruhga o'tkazish",
      "guruh almashtirish",
      "transfer sababi",
      "guruh almashtirish sababi",
      "ustoz farqli",
      "boshlanish sanasi",
      "oy o'rtasida qo'shilish",
      "yozilish",
      "to'lash kerak",
      "taxminan",
      "eski guruhdan qaytadi",
      "oldindan ko'rish",
      "telegram orqali ro'yxatdan o'tish",
      "eng kam to'lov",
      "darsga kirish",
    ],
    yangilangan: "2026-10-03",
  },
  {
    bolim: "oquvchilar",
    sahifa: "muzlatish",
    sarlavha: "Muzlatish va qaytarish",
    qisqacha:
      "Muzlatilgan o'quvchi davomatdan chiqadi, undan dars puli yechilmaydi va oyning o'tilmagan darslar puli balansga qaytadi. Qaytganda oylik kursda faqat qaytgan kundan keyingi darslar hisoblanadi.",
    rollar: [1, 2, 3],
    adr: ["0023", "0043", "0048", "0053", "0064"],
    yollar: ["/students/profile/*"],
    kalitSozlar: [
      "muzlatish",
      "muzlatilgan",
      "qaytarish",
      "faollashtirish",
      "pauza",
      "avtomatik pauza",
      "status o'zgartirish",
      "davomatdan chiqadi",
      "muzlatilgan puli",
      "qaytgan kun",
    ],
    yangilangan: "2026-10-03",
  },
  {
    bolim: "oquvchilar",
    sahifa: "guruhdan-chiqarish",
    sarlavha: "Guruhdan chiqarish va pul",
    qisqacha:
      "Guruhdan chiqarishda pulni qaytarish tartibi tanlanadi. 01.10.2026 dan beri o'quvchi o'zi to'xtatsa va oyning 40% idan ko'pi o'tgan bo'lsa, oylik puli qaytmaydi; hamma guruhda ko'pi bilan 1 ta darsga kelgan o'quvchiga esa oyning to'liq puli qaytadi (sinov darsi). Qaytgan pul balansga tushadi, naqd berilmaydi.",
    rollar: [1, 2, 3],
    adr: ["0043", "0044", "0048", "0060", "0062", "0064"],
    yollar: ["/students/profile/*"],
    kalitSozlar: [
      "guruhdan chiqarish",
      "chiqarish",
      "pul qaytarish",
      "pulni qaytarish tartibi",
      "pul (shartnoma bo'yicha)",
      "shartnoma 6.2",
      "6.2",
      "40%",
      "o'quvchi o'zi to'xtatdi",
      "darajani tugatdi",
      "markaz tashabbusi",
      "sifat bo'yicha shikoyat",
      "pul qaytmaydi",
      "qaytadigan dars yo'q",
      "ketish sababi",
      "sinov darsi",
      "shartnoma 3.5",
      "3.5",
      "bitta darsga kelgan",
      "dars bo'ldimi",
      "javobsiz dars",
      "guruhga qaytarilgan",
      "pul qaytarilmaydigan chegara",
    ],
    yangilangan: "2026-10-03",
  },
  {
    bolim: "oquvchilar",
    sahifa: "chetlatish-va-arxiv",
    sarlavha: "Chetlatish, bitirish, arxiv",
    qisqacha:
      "Chetlatilgan o'quvchining qarzi qoladi va u portal orqali to'lay oladi; bitirish guruh «Tugallangan» qilinganda o'zi bo'ladi. Arxiv faqat xato yoki takroriy yozuv uchun: «O'chirish» belgisi yoki «Statusni o'zgartirish» oynasi orqali qilinadi, kirish hisobi yopiladi, tiklashni faqat CEO qiladi.",
    rollar: [1, 2, 3],
    adr: ["0033", "0035", "0036", "0044", "0048", "0059", "0060"],
    yollar: ["/students/profile/*"],
    kalitSozlar: [
      "chetlatish",
      "chetlatilgan",
      "bitirish",
      "bitirgan",
      "arxiv",
      "arxivga o'tkazish",
      "arxivlash",
      "o'chirish",
      "qayta tiklash",
      "tiklash",
      "dublikat",
      "duplikat",
      "xato yozuv",
      "kirish hisobi yopiladi",
      "statusni o'zgartirish",
      "o'qimayotganlar qarzi",
      "sinov darsi",
    ],
    yangilangan: "2026-10-02",
  },
  {
    bolim: "oquvchilar",
    sahifa: "shartnoma",
    sarlavha: "Shartnoma",
    qisqacha:
      "O'quvchi profilidagi «Shartnomalar» tabida shartnoma tuziladi, PDF qilib chop etiladi va qog'ozda imzolangani belgilanadi. Kurs, narx va Buyurtmachi ma'lumotlari tuzilgan kuni muhrlanadi.",
    rollar: [1, 2, 3],
    adr: ["0075"],
    yollar: ["/students/profile/*"],
    kalitSozlar: [
      "shartnoma",
      "shartnoma tuzish",
      "pdf",
      "chop etish",
      "imzolash",
      "qog'ozda imzolandi",
      "buyurtmachi",
      "ota-ona",
      "vasiy",
      "pasport",
      "dastlabki to'lov",
      "shartnoma raqami",
      "shartnomani bekor qilish",
      "filial vakili",
    ],
    yangilangan: "2026-10-10",
  },
];
