import type { QollanmaSahifa } from "../turlar";

export const tolovlar: QollanmaSahifa[] = [
  {
    bolim: "tolovlar",
    sahifa: "tolov-turlari",
    sarlavha: "Kurs qanday to'lanadi",
    qisqacha:
      "Kurs ikki xil to'lanadi: oylik (har kalendar oy uchun alohida hisob) yoki dars paketi (belgilangan son dars uchun oldindan). Kursning turi Sozlamalar → «Kurslar»da ko'rinadi; uni CEO va filial direktori o'zgartiradi.",
    rollar: [1, 2, 3, 5],
    adr: ["0058"],
    yollar: ["/settings/courses/*"],
    kalitSozlar: [
      "to'lov modeli",
      "to'lov turi",
      "oylik to'lov",
      "dars paketi",
      "sikl to'lovi",
      "sikl",
      "kalendar oy",
      "oylik narx",
      "sikl narxi",
      "sikl darslari",
      "kurs narxi",
      "kurs turi",
      "standart to'lov modeli",
      "modelni almashtirish",
      "dars paketini oylikka o'tkazish",
    ],
    yangilangan: "2026-10-02",
  },
  {
    bolim: "tolovlar",
    sahifa: "oylik-tolov",
    sarlavha: "Oylik to'lov",
    qisqacha:
      "Oylik kursda oy hisobi hisob kunida (odatda 1-sanada) yoziladi va balansdan yechiladi — o'quvchi to'lay oladimi-yo'qmi. Davomat pulga tegmaydi; bekor qilingan dars puli qaytadi (yozuvni o'chirsangiz qayta yechiladi), sababli dars keyingi oy hisobidan ayiriladi. Oyning asosiy raqami — «Hisoblandi / To'landi / Qoldi».",
    rollar: [1, 2, 3, 5],
    adr: ["0042", "0047", "0048", "0053", "0058", "0063"],
    yollar: [],
    kalitSozlar: [
      "oylik hisob",
      "oy hisobi",
      "hisob kuni",
      "hisob-kitob kuni",
      "oyning 2-darsi",
      "muddat",
      "to'lov eslatmasi",
      "oylik to'lov xabari",
      "Telegram xabari",
      "sababli dars krediti",
      "uzrli dars",
      "kredit",
      "bekor qilingan dars",
      "dars puli qaytadi",
      "oy o'rtasida qo'shilgan",
      "chegirma",
      "qarz",
      "muzlatish",
      "hisoblandi",
      "to'landi",
      "qoldi",
      "oy to'lovlari",
      "bekor qilishni o'chirish",
      "qarzdorning 1-darsi",
    ],
    yangilangan: "2026-10-02",
  },
  {
    bolim: "tolovlar",
    sahifa: "dars-paketi",
    sarlavha: "Dars paketi",
    qisqacha:
      "Dars paketida o'quvchi belgilangan son dars (sikl) uchun oldindan to'laydi; pul davomat olinganda yechiladi. «Kelmadi» ham pullik, «Sababli» pulsiz; balans bir darsga yetmasa dars baribir hisoblanadi va o'quvchi qarzdor bo'ladi.",
    rollar: [1, 2, 3, 5],
    adr: ["0047", "0054"],
    yollar: [],
    kalitSozlar: [
      "sikl",
      "sikl darslari",
      "12 dars",
      "20 dars",
      "paket",
      "dars-paket",
      "sikl to'lovi",
      "oldindan to'langan",
      "qisman sikl",
      "kelmadi pullik",
      "sababli pulsiz",
      "balans minusga tushadi",
      "qarzga yozildi",
      "sikl narxi",
      "oxirgi dars narxi",
      "ustoz ulushi kutadi",
    ],
    yangilangan: "2026-10-02",
  },
  {
    bolim: "tolovlar",
    sahifa: "tolov-qayd-qilish",
    sarlavha: "To'lov qayd qilish",
    qisqacha:
      "To'lovni Moliya sahifalaridagi «To'lov qayd qilish» tugmasi bilan yozasiz: o'quvchini tanlaysiz, summa va usulni kiritasiz; oylik kursda oyna pul qaysi darsgacha yetishini ham aytadi. To'lov darhol balansga tushadi va avval qarzni yopadi; chek o'quvchiga Telegramda soat 20:00 da boradi.",
    rollar: [1, 2, 3, 5],
    adr: ["0047", "0058"],
    yollar: ["/payments/pending", "/payments/overview"],
    kalitSozlar: [
      "to'lov qayd qilish",
      "to'lov qabul qilish",
      "to'lov qo'shish",
      "to'lov kiritish",
      "naqd",
      "payme",
      "click",
      "uzum",
      "bank o'tkazmasi",
      "to'lov usuli",
      "summa",
      "chek",
      "kvitansiya",
      "tranzaksiya raqami",
      "tranzaksiyani biriktirish",
      "provayder komissiyasi",
      "kutilyotgan to'lovlar",
      "umumiy ma'lumotlar",
      "oxirgi to'lovlar",
      "qabul qildi",
      "balans",
      "qaysi darsgacha yetadi",
      "qisman to'lov",
      "to'lov va'dasi",
    ],
    yangilangan: "2026-10-02",
  },
  {
    bolim: "tolovlar",
    sahifa: "tolovni-togrilash",
    sarlavha: "To'lovni to'g'rilash",
    qisqacha:
      "Noto'g'ri summa yoki to'lov usulini o'quvchi kartasidagi «To'lovlar» tabidan «Summani to'g'rilash» bilan tuzatasiz. CEO buni istalgan vaqt, direktor va administrator to'lovdan keyingi 72 soat ichida qiladi; kassir to'g'rilay olmaydi.",
    rollar: [1, 2, 3, 5],
    adr: [],
    yollar: [],
    kalitSozlar: [
      "summani to'g'rilash",
      "to'lovni to'g'rilash",
      "to'lovni tuzatish",
      "noto'g'ri summa",
      "usulni o'zgartirish",
      "72 soat",
      "sabab",
      "to'lovni bekor qilish",
      "bekor qilingan to'lov",
      "ortiqcha nol",
      "refund",
      "darslarga sarflangan",
    ],
    yangilangan: "2026-10-02",
  },
  {
    bolim: "tolovlar",
    sahifa: "onlayn-tolov",
    sarlavha: "Payme va Click",
    qisqacha:
      "O'quvchi portalda Payme yoki Click orqali o'zi to'laydi; pul balansga avtomatik tushadi va qarzni yopadi. Uzum hozir onlayn to'lovda ishlamaydi; to'lov bosqichlarini faqat CEO «To'lov tizimlari jurnali»da ko'radi.",
    rollar: [1, 2, 3, 5],
    adr: [],
    yollar: ["/payments/gateway-events"],
    kalitSozlar: [
      "payme",
      "click",
      "uzum",
      "onlayn to'lov",
      "o'quvchi portali",
      "portal",
      "balansni to'ldirish",
      "to'lov tizimlari jurnali",
      "jurnal",
      "xavfsizlik xatosi",
      "tranzaksiya raqami",
      "tayyorlash",
      "yakunlash",
      "tez kunda",
      "komissiya",
    ],
    yangilangan: "2026-09-30",
  },
  {
    bolim: "tolovlar",
    sahifa: "pul-qaytarish",
    sarlavha: "Pulni qaytarish va yechib olish",
    qisqacha:
      "Pulni qaytarish o'quvchiga pulini qaytarib berishni yozadi: pul faqat erkin balansdan va hali o'tilmagan oldindan to'langan darslardan olinadi. «Yechib olish» balansdagi pulni o'quvchiga bermay markaz hisobiga o'tkazadi: u yechib olingan oyning daromadi bo'ladi (oy tanlanmaydi) va ixtiyoriy ravishda ustozga ulush yoziladi; ikkalasini CEO, direktor va administrator qiladi.",
    rollar: [1, 2, 3],
    adr: ["0055", "0058"],
    yollar: [],
    kalitSozlar: [
      "pulni qaytarish",
      "qaytarish",
      "refund",
      "yechib olish",
      "markaz hisobiga o'tkazish",
      "o'quvchiga qaytarish",
      "qaytarish mumkin",
      "qaytarish usuli",
      "oldindan to'langan darslar",
      "balansdan olindi",
      "ustoz balansiga yozilsinmi",
      "qaytarilgan pul",
      "balansdan yechib olingan",
      "foyda tarkibi",
      "oy daromadi",
    ],
    yangilangan: "2026-10-02",
  },
  {
    bolim: "tolovlar",
    sahifa: "qarzdorlik",
    sarlavha: "Qarzdorlik",
    qisqacha:
      "«Qarzdorlik» sahifasi kim qarzdor, qancha va qachondan beri ekanini ko'rsatadi. Qarz ikki alohida raqamda: o'qiyotganlar qarzi va o'qimayotganlar qarzi. Besh tab qarzdorlarni, markaz qoplagan pulni, qarzning oylarini, kechirilganlarni va muzlatilganlar pulini ochadi. Qarzni kechirish CEO qarori bilan o'chiq.",
    rollar: [1, 2, 3, 5],
    adr: ["0058", "0059"],
    yollar: ["/payments/debt"],
    kalitSozlar: [
      "qarzdorlik",
      "qarzdorlar",
      "qarz",
      "qarzdor",
      "jami qarz",
      "o'rtacha qarz",
      "qachondan beri",
      "markaz qoplagani",
      "oylik qarzdorlik",
      "kechirilganlar",
      "muzlatilgan puli",
      "natijani kiritish",
      "to'lov va'dasi",
      "muddati o'tgan",
      "sana belgilangan",
      "qarzni kechirish",
      "qarz kechirishga ruxsat",
      "hisobdan chiqarish",
      "kutilyotgan to'lovlar",
      "kechirishni qaytarib olish",
      "o'qiyotganlar qarzi",
      "o'qimayotganlar qarzi",
      "shu oy qarzi",
      "eski qarz",
    ],
    yangilangan: "2026-10-02",
  },
];
