// Central Phosphor icon map for the Lumio student portal. Phosphor's rounded,
// weight-aware glyphs (bold / fill for active state) match the chunky Baloo
// aesthetic far better than the thin lucide outline used elsewhere in the ERP.
// Named re-exports so screens and nav reference icons from one place and the
// bundler tree-shakes what we don't use.
export {
  House,
  CalendarBlank,
  Sparkle,
  Wallet,
  DotsThreeOutline,
  List,
  QrCode,
  Gear,
  User,
  Question,
  Info,
  SignOut,
  SignIn,
  CaretRight,
  CaretLeft,
  CaretLineLeft,
  CaretLineRight,
  Camera,
  Check,
  CheckCircle,
  X,
  Users,
  Clock,
  ArrowUpRight,
  Sun,
  Moon,
  Desktop,
  GraduationCap,
  MapPin,
  Phone,
  TelegramLogo,
  Chalkboard,
  BookOpen,
  ChatCircleDots,
  CreditCard,
  WarningCircle,
  CloudSlash,
  ChartLineUp,
  IdentificationCard,
  Lightning,
  CircleNotch,
  Bell,
  Trash,
  PencilSimple,
  Image as ImageIcon,
  Eye,
  EyeSlash,
  // Radio screen + persistent player.
  Radio,
  Broadcast,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  SpeakerHigh,
  SpeakerSlash,
  ArrowClockwise,
  Heart,
  CaretDown,
  // Radio category glyphs.
  Newspaper,
  MusicNotes,
  Waveform,
  PianoKeys,
  VinylRecord,
} from "@phosphor-icons/react";

export type { Icon, IconWeight } from "@phosphor-icons/react";
